### ISSUE TITLE
Grant Permissions

### ISSUE THREAD

**Issue by DenOkhota** [denysOkhota/git_dive_in#1]
subj

**Comment by DenOkhota** [comment]
I changed a code:

```css
body {
  margin: 0;
  text-align: center;
  background-color: #322eff;
  color: #f6f0ee;
}
```
